---
# FMC Common Role Default Variables

# Output Directories
config_output_dir: "../../outputs/configs"
trace_output_dir: "../../outputs/packet_traces"
report_output_dir: "../../outputs/reports"
log_output_dir: "../../outputs/logs"

# API Settings
api_timeout: 30
api_retries: 3
api_delay: 5
validate_certs: false
fmc_protocol: "https"

# Default domain UUID (FMC default)
domain_uuid: "e276abec-e0f2-11e3-8169-6d9ed49b625f"

# Logging Settings
log_level: "INFO"
log_to_file: true
log_rotation: true
max_log_files: 10

# Feature flags
extract_hardening_config: true
manage_rules: true
run_packet_tracer: false
generate_html_reports: true
