---
collections:
  - name: ansible.posix
    version: ">=2.0.0"
  - name: community.general
    version: ">=10.7.0"
  - name: ansible.utils
    version: ">=2.10.3,<7.0.0" 
  - name: cisco.fmcansible
    version: ">=1.0.2"
