---
# FMC Common Tasks - Shared functionality across all FMC roles

- name: Set timestamp variable
  set_fact:
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"
  when: timestamp is not defined

- name: Create all output directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ config_output_dir }}"
    - "{{ trace_output_dir }}"
    - "{{ report_output_dir }}"
    - "{{ log_output_dir }}"
  delegate_to: localhost
  run_once: true

- name: Validate FMC connection parameters
  fail:
    msg: "Required FMC parameter {{ item }} is not defined"
  when: vars[item] is not defined or vars[item] == ""
  loop:
    - fmc_host
    - fmc_username
    - fmc_password

- name: Set default FMC protocol if not defined
  set_fact:
    fmc_protocol: "https"
  when: fmc_protocol is not defined

- name: Set default domain UUID if not defined
  set_fact:
    domain_uuid: "e276abec-e0f2-11e3-8169-6d9ed49b625f"
  when: domain_uuid is not defined
