---
# FTD Security Hardening Role Default Variables - Security Hardening Benchmark Implementation

# ================================
# ROLE BEHAVIOR SETTINGS
# ================================
ftd_hardening_enabled: true
ftd_hardening_json_output: false
fail_on_hardening_error: true
ftd_hardening_dry_run: false
debug_mode: false

# ================================
# 4.1 GENERAL SECURITY CONTROL LIST
# ================================

# 4.1.1 Hostname Configuration
ftd_hostname_config:
  enabled: true
  enforce_naming_convention: true
  # Format: <DataCenterLocation>-<NetworkZone>-<Institution/cluster>-<DevicePurpose><RunningNumbers>
  naming_pattern: "^[A-Z]{2,4}-[A-Z]{2,8}-[A-Z0-9]{2,12}-[A-Z0-9]{2,8}[0-9]{1,3}$"
  validate_uniqueness: true

# 4.1.2 Warning Banner Configuration
ftd_banner_config:
  enabled: true
  login_banner: |
    THIS SYSTEM IS SOLELY FOR THE USE OF AUTHORIZED USERS.
    INDIVIDUALS USING THIS COMPUTER SYSTEM WITHOUT AUTHORITY,
    OR IN EXCESS OF THEIR AUTHORITY, ARE SUBJECT TO HAVING
    ALL OF THEIR ACTIVITIES ON THIS SYSTEM MONITORED AND RECORDED
    BY SYSTEM PERSONNEL. IN THE COURSE OF MONITORING INDIVIDUALS
    IMPROPERLY USING THIS SYSTEM, OR IN THE COURSE OF SYSTEM
    MAINTENANCE, THE ACTIVITIES OF AUTHORIZED USERS MAY ALSO
    BE MONITORED. ANYONE USING THIS SYSTEM EXPRESSLY CONSENTS
    TO SUCH MONITORING AND IS ADVISED THAT IF SUCH MONITORING
    REVEALS POSSIBLE EVIDENCE OF CRIMINAL ACTIVITY, SYSTEM
    PERSONNEL MAY PROVIDE THE EVIDENCE FROM SUCH MONITORING
    TO LAW ENFORCEMENT OFFICIALS.
  motd_banner: |
    WARNING: This system is for authorized users only.
    All activities are monitored and logged.

# 4.1.3 NTP Configuration
ftd_ntp_config:
  enabled: true
  ntp_servers:
    - server: "time.nist.gov"
      preferred: true
      authentication_key_id: null
    - server: "pool.ntp.org"
      preferred: false
      authentication_key_id: null
  timezone: "UTC"
  ntp_authentication:
    enabled: false  # Enable if NTP authentication is required
    keys: []

# 4.1.4 Syslog Configuration
ftd_syslog_config:
  enabled: true
  syslog_servers:
    # OIP/CSA syslog servers (to be updated with actual IPs)
    - server: "10.247.54.100"  # Replace with actual OIP server
      port: 514
      protocol: "UDP"
      facility: "LOCAL0"
      severity: "informational"
      description: "OIP Syslog Server"
    - server: "10.247.54.101"  # Replace with actual CSA server
      port: 514
      protocol: "UDP"
      facility: "LOCAL1"
      severity: "informational"
      description: "CSA Syslog Server"
  # Remove old ELK/Splunk servers
  remove_old_servers:
    - "old.elk.server.com"
    - "old.splunk.server.com"

# ================================
# 4.2 HEALTH MONITORING
# ================================

# 4.2.1 SNMP Settings
ftd_snmp_config:
  enabled: true
  version: "v3"
  users:
    - username: "snmp_admin"
      authentication_type: "SHA"
      authentication_password: "change_this_auth_password"
      privacy_protocol: "AES128"
      privacy_password: "change_this_priv_password"
  management_hosts:
    # OIP/CSPC servers (to be updated with actual IPs)
    - host: "10.247.54.102"  # Replace with actual OIP server
      description: "OIP SNMP Management Server"
    - host: "10.247.54.103"  # Replace with actual CSPC server
      description: "CSPC SNMP Management Server"
  # Remove old SNMP management hosts
  remove_old_hosts:
    - "old.snmp.management.server.com"

# 4.2.2 Health Monitor Alerts
ftd_health_monitoring:
  enabled: true
  policy_run_interval_minutes: 5
  alerts:
    amp_for_endpoints_status: true
    amp_for_firepower_status: true
    appliance_heartbeat: true
    automatic_application_bypass_status: true
    backlog_status: true
    card_reset: false  # Explicitly disabled
    cluster_failover_status: true
    cpu_usage:
      enabled: true
      warning_threshold: 80
      critical_threshold: 90
    disk_status: true
    disk_usage:
      enabled: true
      warning_threshold: 85
      critical_threshold: 90
    hardware_alarms: true
    ha_status: true
    health_monitor_process: true
    host_limit: true
    inline_link_mismatch_alarms: true
    interface_status: true
    intrusion_and_file_event_rate: true
    ise_connection_status_monitor: true
    link_state_propagation: true
    local_malware_analysis: true
    memory_usage:
      enabled: true
      warning_threshold: 80
      critical_threshold: 90
    platform_faults: true
    power_supply: true
    process_status: true
    reconfiguring_detection: true
    rrd_server_process: true
    security_intelligence: true
    smart_license_monitor: true

# ================================
# 4.3 MANAGEMENT ACCESS CONTROL LIST
# ================================

# 4.3.1 SSH Access Control - CRITICAL SECURITY
ftd_ssh_access_control:
  enabled: true
  allowed_networks:
    # H-Cloud Management Servers (HTTPS, SSH)
    - network: "10.247.54.62"
      mask: "255.255.255.255"
      description: "H-Cloud Management Server"
    # - network: "10.247.54.20"
    #   mask: "255.255.255.252"
    #   description: "H-Cloud Management Servers 20-22"
    # - network: "10.247.54.39"
    #   mask: "255.255.255.248"
    #   description: "H-Cloud Management Servers 39-43"
    # - network: "10.247.54.122"
    #   mask: "255.255.255.248"
    #   description: "H-Cloud Management Servers 122-129"
    # - network: "10.247.54.24"
    #   mask: "255.255.255.255"
    #   description: "H-Cloud Management Server"
    # - network: "10.247.54.77"
    #   mask: "255.255.255.252"
    #   description: "H-Cloud Management Servers 77-79"
    # - network: "10.247.22.80"
    #   mask: "255.255.255.254"
    #   description: "H-Cloud Management Servers 80-81"
    # - network: "10.247.54.81"
    #   mask: "255.255.255.254"
    #   description: "H-Cloud Management Servers 81-82"
    
    # # H-Cloud Security Utility Servers (HTTPS, SSH)
    # - network: "10.247.22.4"
    #   mask: "255.255.255.255"
    #   description: "H-Cloud Security Utility Server"
    # - network: "10.247.54.4"
    #   mask: "255.255.255.255"
    #   description: "H-Cloud Security Utility Server"
    
    # # Security Compliance Server (HTTPS, SSH)
    # - network: "10.247.17.62"
    #   mask: "255.255.255.255"
    #   description: "Security Compliance Server"
    # - network: "10.247.22.135"
    #   mask: "255.255.255.255"
    #   description: "Security Compliance Server"
    
    # # Algosec Server (HTTPS, SSH) [Optional]
    # - network: "10.247.126.25"
    #   mask: "255.255.255.252"
    #   description: "Algosec Servers 25-27"
    
    # # EVMS Scanner IP (HTTPS, SSH)
    # - network: "10.247.17.106"
    #   mask: "255.255.255.255"
    #   description: "EVMS Scanner"
    # - network: "10.247.49.98"
    #   mask: "255.255.255.255"
    #   description: "EVMS Scanner"

# 4.3.2 Session Timeout Configuration
ftd_session_timeout:
  enabled: true
  browser_timeout_minutes: 15
  shell_timeout_minutes: 15

# 4.3.3 Local Account Password Policy
ftd_password_policy:
  enabled: true
  min_length: 15
  complexity_categories_required: 2
  categories:
    uppercase: true      # A-Z
    lowercase: true      # a-z
    numbers: true        # 0-9
    special_chars: true  # Special characters
  password_strength_checking: true
  apply_to_local_users: true

# 4.3.4 External Authentication (LDAPS)
ftd_external_auth:
  enabled: false  # Set to true when LDAPS servers are available
  ldaps_servers:
    primary:
      server: "ldaps.primary.domain.com"
      port: 636
      base_dn: "dc=domain,dc=com"
      bind_dn: "cn=admin,dc=domain,dc=com"
      bind_password: "change_this_password"
    secondary:
      server: "ldaps.secondary.domain.com"
      port: 636
      base_dn: "dc=domain,dc=com"
      bind_dn: "cn=admin,dc=domain,dc=com"
      bind_password: "change_this_password"
    tertiary:  # Optional 3rd LDAPS server
      server: "ldaps.tertiary.domain.com"
      port: 636
      base_dn: "dc=domain,dc=com"
      bind_dn: "cn=admin,dc=domain,dc=com"
      bind_password: "change_this_password"
  authentication_order:
    - "local"
    - "ldap"
  secure_protocols_only: true

# ================================
# PLATFORM SETTINGS POLICY
# ================================
ftd_platform_settings:
  policy_name: "FTD_Security_Hardening_Benchmark_Policy"
  description: "FTD Security Hardening Benchmark Compliance Policy - Implements all required security controls"

# ================================
# VERIFICATION AND COMPLIANCE
# ================================
ftd_verification:
  enabled: true
  ssh_access_verification: true
  session_timeout_verification: true
  password_policy_verification: true
  hostname_verification: true
  banner_verification: true
  ntp_verification: true
  syslog_verification: true
  snmp_verification: true
  health_monitoring_verification: true
  external_auth_verification: true
  policy_deployment_verification: true

# ================================
# DEFAULT HARDENING RESULTS
# ================================
ftd_hardening_results:
  # 4.1 General Security Control List
  hostname_configured: false
  banner_configured: false
  ntp_configured: false
  syslog_configured: false
  
  # 4.2 Health Monitoring
  snmp_configured: false
  health_monitoring_configured: false
  
  # 4.3 Management Access Control List
  ssh_access_configured: false
  session_timeout_configured: false
  password_policy_configured: false
  external_auth_configured: false
  
  # Overall Status
  platform_policy_deployed: false
  verification_passed: false
  benchmark_compliance: false

# ================================
# OPERATIONAL SETTINGS
# ================================
ftd_max_concurrent_operations: 3
api_timeout: 30
report_output_dir: "./"

