---
# FMC Connection Test Tasks using cisco.fmcansible collection

- name: Test FMC Connection and Get Server Version
  cisco.fmcansible.fmc_configuration:
    operation: getAllServerVersion
  register: server_version_test
  failed_when: false

- name: Degug Server Version Test
  debug:
    var: server_version_test
  when: debug_mode | default(false) | bool

- name: Display Server Version Test Results
  debug:
    msg:
      - "FMC Server Version Test Results:"
      - "Host: {{ ansible_host }}"
      - "Status: {{ 'SUCCESS' if server_version_test.response is defined else 'FAILED' }}"
      - "FMC Version: {{ server_version_test.response['items'][0].serverVersion | default('Unknown') }}"
      - "Model: {{ server_version_test.response['items'][0].model | default('Unknown') }}"
      - "Hostname: {{ server_version_test.response['items'][0].hostname | default('Unknown') }}"
      - "Uptime: {{ server_version_test.response['items'][0].uptime | default('Unknown') }}"
  when: server_version_test.response is defined

- name: Display Server Version Test Failure
  debug:
    msg:
      - "FMC Server Version Test Results:"
      - "Status: FAILED"
      - "Error: {{ server_version_test.msg | default('Connection test failed') }}"
  when: server_version_test.response is not defined

- name: Test Domain Access
  cisco.fmcansible.fmc_configuration:
    operation: getAllDomain
  register: domain_test
  failed_when: false

- name: Debug Domain Test
  debug:
    var: domain_test
  when: debug_mode | default(false) | bool

- name: Display Domain Test Results
  debug:
    msg:
      - "FMC Domain Access Test Results:"
      - "Status: {{ 'SUCCESS' if domain_test.response is defined else 'FAILED' }}"
      - "Domains Found: {{ domain_test.response['items'] | length | default(0) }}"
      - "Available Domains:"
  when: domain_test.response is defined

- name: List Available Domains
  debug:
    msg: "  - {{ item.name }} (UUID: {{ item.uuid }})"
  loop: "{{ domain_test.response['items'] | default([]) }}"
  when: domain_test.response is defined

- name: Test Access Policy Access (if domain test successful)
  cisco.fmcansible.fmc_configuration:
    operation: getAllAccessPolicy
    path_params:
      domainUUID: "{{ domain_test.response['items'][0].uuid }}"
  register: access_policy_test
  when: domain_test.response is defined and domain_test.response['items'] | length > 0
  failed_when: false

- name: Display Access Policy Test Results
  debug:
    msg:
      - "FMC Access Policy Test Results:"
      - "Status: {{ 'SUCCESS' if access_policy_test.response is defined else 'FAILED' }}"
      - "Access Policies Found: {{ access_policy_test.response | length | default(0) }}"
  when: 
    - domain_test.response is defined
    - access_policy_test is defined

- name: Overall Test Summary
  debug:
    msg:
      - "=== FMC CONNECTION TEST SUMMARY ==="
      - "FMC Host: {{ ansible_host }}"
      - "Server Version: {{ 'PASS' if server_version_test.response is defined else 'FAIL' }}"
      - "Domain Access: {{ 'PASS' if domain_test.response is defined else 'FAIL' }}"
      - "Access Policy Access: {{ 'PASS' if access_policy_test.response is defined else 'FAIL' if domain_test.response is defined else 'SKIPPED' }}"
      - "Overall Status: {{ 'READY FOR AUTOMATION' if (server_version_test.response is defined and domain_test.response is defined) else 'NEEDS ATTENTION' }}"

- name: Set connection test results
  set_fact:
    fmc_connection_test_passed: "{{ server_version_test.response is defined and domain_test.response is defined }}"
    fmc_server_version: "{{ server_version_test.response.items[0].serverVersion | default('Unknown') }}"
    fmc_domain_uuid: "{{ domain_test.response.items[0].uuid | default('') }}"
    fmc_domain_name: "{{ domain_test.response.items[0].name | default('') }}"

- name: Fail if critical tests failed
  fail:
    msg: "Critical FMC connection tests failed. Please check credentials and connectivity."
  when: 
    - not fmc_connection_test_passed
    - fail_on_connection_error | default(true) | bool
