---
# FMC Connection Test Tasks
- name: Test FMC Connectivity
  uri:
    url: "{{ fmc_protocol }}://{{ ansible_host }}/api/fmc_platform/v1/info/serverversion"
    method: GET
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ api_timeout | default(30) }}"
  register: connectivity_test
  failed_when: false

- name: Display Connectivity Results
  debug:
    msg:
      - "FMC Connectivity Test Results:"
      - "Host: {{ ansible_host }}"
      - "Status: {{ 'SUCCESS' if connectivity_test.status == 401 or connectivity_test.status == 200 else 'FAILED' }}"
      - "HTTP Status: {{ connectivity_test.status }}"
      - "Note: Status 401 is expected without authentication - this confirms FMC is reachable"

- name: Test FMC Authentication
  uri:
    url: "{{ fmc_protocol }}://{{ ansible_host }}/api/fmc_platform/v1/auth/generatetoken"
    method: POST
    user: "{{ fmc_username }}"
    password: "{{ fmc_password }}"
    validate_certs: "{{ validate_certs }}"
    force_basic_auth: yes
    timeout: "{{ api_timeout | default(30) }}"
  register: auth_test
  failed_when: false

- name: Display Authentication Results
  debug:
    msg:
      - "FMC Authentication Test Results:"
      - "Status: {{ 'SUCCESS' if auth_test.status == 204 else 'FAILED' }}"
      - "HTTP Status: {{ auth_test.status }}"
      - "Auth Token Present: {{ 'YES' if auth_test.x_auth_access_token is defined else 'NO' }}"
      - "Domain UUID: {{ auth_test.domain_uuid | default('Not provided') }}"

- name: Test API Access (if authentication successful)
  uri:
    url: "{{ fmc_protocol }}://{{ ansible_host }}/api/fmc_platform/v1/info/serverversion"
    method: GET
    headers:
      X-auth-access-token: "{{ auth_test.x_auth_access_token }}"
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ api_timeout | default(30) }}"
  register: api_test
  when: auth_test.status == 204
  failed_when: false

- name: Display API Test Results
  debug:
    msg:
      - "FMC API Access Test Results:"
      - "Status: {{ 'SUCCESS' if api_test.status == 200 else 'FAILED' }}"
      - "FMC Version: {{ api_test.json.serverVersion | default('Unknown') }}"
      - "Build: {{ api_test.json.build | default('Unknown') }}"
  when: auth_test.status == 204

- name: Test Domain Access
  uri:
    url: "{{ fmc_protocol }}://{{ ansible_host }}/api/fmc_config/v1/domain/{{ domain_uuid }}/policy/accesspolicies"
    method: GET
    headers:
      X-auth-access-token: "{{ auth_test.x_auth_access_token }}"
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ api_timeout | default(30) }}"
  register: domain_test
  when: auth_test.status == 204
  failed_when: false

- name: Display Domain Test Results
  debug:
    msg:
      - "FMC Domain Access Test Results:"
      - "Status: {{ 'SUCCESS' if domain_test.status == 200 else 'FAILED' }}"
      - "Domain UUID: {{ domain_uuid }}"
      - "Access Policies Found: {{ domain_test.json.paging.count | default(0) }}"
  when: auth_test.status == 204

- name: Overall Test Summary
  debug:
    msg:
      - "=== FMC CONNECTION TEST SUMMARY ==="
      - "FMC Host: {{ ansible_host }}"
      - "Connectivity: {{ 'PASS' if connectivity_test.status == 401 or connectivity_test.status == 200 else 'FAIL' }}"
      - "Authentication: {{ 'PASS' if auth_test.status == 204 else 'FAIL' }}"
      - "API Access: {{ 'PASS' if api_test.status == 200 else 'FAIL' if auth_test.status == 204 else 'SKIPPED' }}"
      - "Domain Access: {{ 'PASS' if domain_test.status == 200 else 'FAIL' if auth_test.status == 204 else 'SKIPPED' }}"
      - "Overall Status: {{ 'READY FOR AUTOMATION' if (auth_test.status == 204 and api_test.status == 200 and domain_test.status == 200) else 'NEEDS ATTENTION' }}"

- name: Set connection test results
  set_fact:
    fmc_connection_test_passed: "{{ auth_test.status == 204 and api_test.status == 200 and domain_test.status == 200 }}"
    fmc_auth_token: "{{ auth_test.x_auth_access_token | default('') }}"
    fmc_domain_uuid: "{{ auth_test.domain_uuid | default(domain_uuid) }}"

- name: Fail if critical tests failed
  fail:
    msg: "Critical FMC connection tests failed. Please check credentials and connectivity."
  when: 
    - not fmc_connection_test_passed
    - fail_on_connection_error | default(true) | bool
