---
- name: FMC Complete Automation Suite (Role-based)
  hosts: fmc01
  gather_facts: false
  
  roles:
    # Common setup and validation
    - role: fmc_common
      tags: ['always', 'common']

    # FMC Connection test
    - role: fmc_connection
      tags: ['connection', 'test']
      vars:
        fail_on_connection_error: true

    # FTD Device discovery and connectivity testing
    - role: ftd_discovery
      tags: ['ftd', 'discovery', 'test']
      when: discover_ftd_devices | default(true) | bool

    # FMC Hardening configuration extraction
    - role: fmc_hardening
      tags: ['fmc', 'hardening', 'config']
      when: extract_hardening_config | default(true) | bool

    # FTD Security Hardening
    - role: ftd_hardening
      tags: ['ftd', 'hardening', 'security']
      when: 
        - ftd_hardening_enabled | default(true) | bool
        - ftd_devices_found | default(false) | bool

    # Rule management (time-based)
    - role: fmc_rule_management
      tags: ['rules', 'management', 'fmc']
      when: 
        - manage_rules | default(true) | bool
        - rule_expiry_check_enabled | default(true) | bool

    # FTD Rule management (device-level)
    - role: ftd_rule_management
      tags: ['ftd', 'rules', 'management']
      when: 
        - manage_ftd_rules | default(true) | bool
        - ftd_devices_found | default(false) | bool
        - ftd_rule_management_enabled | default(true) | bool

    # Packet tracer
    - role: fmc_packet_tracer
      tags: ['packet', 'tracer']
      when: 
        - run_packet_tracer | default(false) | bool
        - source_ip is defined
        - dest_ip is defined
        - interface_id is defined
        - interface_name is defined
        - interface_type is defined

  post_tasks:
    - name: Display Final Summary
      debug:
        msg:
          - "=========================================="
          - "    AUTOMATION SUITE COMPLETED"
          - "=========================================="
          - "All tasks completed successfully!"
          - "Reports generated in: {{ report_output_dir }}"
          - "Logs available in: {{ log_output_dir }}"
          - "=========================================="
      tags: ['always']
