---
# Password Policy Configuration
# Configure password policy settings for enhanced security

- name: Get Current Local Realm Users for Password Policy Analysis
  cisco.fmcansible.fmc_configuration:
    operation: getAllLocalRealmUser
    path_params:
      domainUUID: "{{ domain_uuid }}"
  register: local_users
  failed_when: false
  when: password_policy_enabled | bool

- name: Debug Local Users Configuration
  debug:
    var: local_users
  when: 
    - password_policy_enabled | bool
    - debug_mode | default(false) | bool

- name: Get Current Realm Configuration
  cisco.fmcansible.fmc_configuration:
    operation: getAllRealm
    path_params:
      domainUUID: "{{ domain_uuid }}"
  register: realm_config
  failed_when: false
  when: password_policy_enabled | bool

- name: Debug Realm Configuration
  debug:
    var: realm_config
  when: 
    - password_policy_enabled | bool
    - debug_mode | default(false) | bool

- name: Analyze Current Password Policy Configuration
  set_fact:
    local_users_available: "{{ local_users.response is defined }}"
    realm_config_available: "{{ realm_config.response is defined }}"
    total_local_users: "{{ local_users.response['items'] | length if (local_users.response is defined and local_users.response['items'] is defined) else 0 }}"
    realm_count: "{{ realm_config.response['items'] | length if (realm_config.response is defined and realm_config.response['items'] is defined) else 0 }}"
  when: password_policy_enabled | bool

- name: Check Password Policy Compliance
  set_fact:
    password_policy_compliant: "{{ realm_config_available | default(false) and local_users_available | default(false) }}"
    password_policy_recommendation: |
      Configure strong password policy with the following requirements:
      - Minimum password length: {{ min_password_length | default(12) }} characters
      - Require uppercase letters: {{ require_uppercase | default(true) }}
      - Require lowercase letters: {{ require_lowercase | default(true) }}
      - Require numbers: {{ require_numbers | default(true) }}
      - Require special characters: {{ require_special_chars | default(true) }}
      - Password history: {{ password_history_count | default(5) }} previous passwords
      - Password expiration: {{ password_expiry_days | default(90) }} days
      - Account lockout threshold: {{ lockout_threshold | default(3) }} failed attempts
      - Account lockout duration: {{ lockout_duration_minutes | default(30) }} minutes
  when: password_policy_enabled | bool

- name: Record Password Policy Configuration Status
  set_fact:
    compliance_results: "{{ compliance_results | default({}) | combine({
      'password_policy_compliance': {
        'status': password_policy_compliant | default(false),
        'local_users_available': local_users_available | default(false),
        'realm_config_available': realm_config_available | default(false),
        'total_local_users': total_local_users | default(0),
        'realm_count': realm_count | default(0),
        'compliant': password_policy_compliant | default(false),
        'applied': false,
        'recommendation': password_policy_recommendation | default('Configure strong password policy through FMC GUI'),
        'policy_requirements': {
          'min_password_length': min_password_length | default(12),
          'require_uppercase': require_uppercase | default(true),
          'require_lowercase': require_lowercase | default(true),
          'require_numbers': require_numbers | default(true),
          'require_special_chars': require_special_chars | default(true),
          'password_history_count': password_history_count | default(5),
          'password_expiry_days': password_expiry_days | default(90),
          'lockout_threshold': lockout_threshold | default(3),
          'lockout_duration_minutes': lockout_duration_minutes | default(30)
        }
      } }) }}"
  when: password_policy_enabled | bool

- name: Display Password Policy Compliance Status
  debug:
    msg:
      - "Password Policy Compliance Check:"
      - "Local Users Available: {{ local_users_available | default(false) }}"
      - "Realm Configuration Available: {{ realm_config_available | default(false) }}"
      - "Total Local Users: {{ total_local_users | default(0) }}"
      - "Realm Count: {{ realm_count | default(0) }}"
      - "Password Policy Compliant: {{ password_policy_compliant | default(false) }}"
      - ""
      - "Required Policy Settings:"
      - "- Minimum Password Length: {{ min_password_length | default(12) }} characters"
      - "- Require Uppercase: {{ require_uppercase | default(true) }}"
      - "- Require Lowercase: {{ require_lowercase | default(true) }}"
      - "- Require Numbers: {{ require_numbers | default(true) }}"
      - "- Require Special Characters: {{ require_special_chars | default(true) }}"
      - "- Password History: {{ password_history_count | default(5) }} passwords"
      - "- Password Expiry: {{ password_expiry_days | default(90) }} days"
      - "- Lockout Threshold: {{ lockout_threshold | default(3) }} attempts"
      - "- Lockout Duration: {{ lockout_duration_minutes | default(30) }} minutes"
  when: password_policy_enabled | bool

- name: Manual Configuration Instructions for Password Policy
  debug:
    msg: |
      MANUAL PASSWORD POLICY CONFIGURATION REQUIRED:
      
      The FMC API does not provide direct password policy configuration.
      Please configure password policy manually through the FMC GUI:
      
      1. Navigate to System > Users > Authentication
      2. Configure Local Authentication Settings:
         a. Minimum Password Length: {{ min_password_length | default(12) }} characters
         b. Password Complexity Requirements:
            - At least {{ require_uppercase | default(true) | ternary('1', '0') }} uppercase letter
            - At least {{ require_lowercase | default(true) | ternary('1', '0') }} lowercase letter  
            - At least {{ require_numbers | default(true) | ternary('1', '0') }} number
            - At least {{ require_special_chars | default(true) | ternary('1', '0') }} special character
         c. Password History: Remember {{ password_history_count | default(5) }} previous passwords
         d. Password Expiration: {{ password_expiry_days | default(90) }} days
      
      3. Configure Account Lockout Policy:
         a. Navigate to System > Users > Account Lockout
         b. Enable Account Lockout
         c. Failed Login Attempts: {{ lockout_threshold | default(3) }}
         d. Lockout Duration: {{ lockout_duration_minutes | default(30) }} minutes
         e. Reset Failed Attempts Counter: {{ lockout_reset_time | default(24) }} hours
      
      4. Configure Session Security:
         a. Navigate to System > Users > Session Settings
         b. Enable concurrent session limits
         c. Set maximum concurrent sessions per user: {{ max_concurrent_sessions | default(2) }}
         d. Enable session timeout on inactivity
      
      5. Additional Security Measures:
         a. Navigate to System > Logging > Audit
         b. Enable authentication event logging
         c. Configure log retention for compliance
         d. Set up alerts for multiple failed login attempts
      
      6. User Management Best Practices:
         a. Regularly review user accounts for inactive users
         b. Implement principle of least privilege
         c. Use role-based access control
         d. Regularly audit user permissions
      
      7. Click Save to apply all changes
      
      Security Recommendations:
      - Enforce password policy for all user types (local, LDAP, SSO)
      - Implement multi-factor authentication where possible
      - Regular password policy reviews and updates
      - User security awareness training
  when: 
    - password_policy_enabled | bool
    - not (password_policy_compliant | default(false))

- name: Display Local Users Summary
  debug:
    msg: |
      Local Users Summary:
      {% for user in local_users.response['items'] | default([]) %}
      - User: {{ user.name | default('Unknown') }}
        Role: {{ user.userRole | default('Unknown') }}
        Enabled: {{ user.enabled | default(false) }}
      {% endfor %}
      
      Total Local Users: {{ total_local_users | default(0) }}
      Note: Review each user account for compliance with security policies
  when: 
    - password_policy_enabled | bool
    - local_users_available | default(false)
    - total_local_users | default(0) | int > 0
    - debug_mode | default(false) | bool

- name: Warn if Password Policy is Non-Compliant
  fail:
    msg: |
      PASSWORD POLICY COMPLIANCE FAILURE:
      Current password policy configuration does not meet security requirements.
      
      Required Security Settings:
      - Minimum Password Length: {{ min_password_length | default(12) }} characters
      - Password Complexity: Uppercase, lowercase, numbers, special characters
      - Password History: {{ password_history_count | default(5) }} previous passwords
      - Password Expiration: {{ password_expiry_days | default(90) }} days maximum
      - Account Lockout: {{ lockout_threshold | default(3) }} failed attempts
      - Lockout Duration: {{ lockout_duration_minutes | default(30) }} minutes
      
      Security Risks:
      - Weak passwords increase vulnerability to brute force attacks
      - No password expiration allows compromised passwords to remain valid
      - No account lockout enables unlimited password guessing attempts
      - Poor password history allows password reuse
      
      Manual Action Required:
      1. Navigate to System > Users > Authentication
      2. Configure password complexity requirements
      3. Set password expiration and history policies
      4. Configure account lockout settings
      5. Enable authentication audit logging
      6. Implement regular password policy reviews
  when: 
    - password_policy_enabled | bool
    - not (password_policy_compliant | default(false))
    - validate_compliance | bool
  ignore_errors: "{{ not validate_compliance }}"

- name: Log Password Policy Configuration Status
  debug:
    msg: |
      Password policy configuration analysis completed:
      - Local Users Found: {{ total_local_users | default(0) }}
      - Realm Configuration Available: {{ realm_config_available | default(false) }}
      - Manual Configuration Required: True (API limitations)
      - Compliance Status: {{ 'MANUAL_REVIEW_REQUIRED' if not (password_policy_compliant | default(false)) else 'COMPLIANT' }}
      
      Next Steps:
      1. Review current password policy settings in FMC GUI
      2. Implement recommended security configurations
      3. Document policy changes for compliance audit
      4. Schedule regular policy reviews
  when: 
    - password_policy_enabled | bool
    - apply_hardening | bool

