---
# Password Policy Configuration and Validation
# Local Account Password Policy per security requirements

- name: Get Current Password Policy Configuration
  cisco.fmcansible.fmc_configuration:
    operation: getPasswordPolicy
  register: current_password_policy
  failed_when: false
  when: password_policy_enabled | bool

- name: Debug Current Password Policy Configuration
  debug:
    var: current_password_policy
  when: password_policy_enabled | bool

- name: Get Local User Accounts
  cisco.fmcansible.fmc_configuration:
    operation: getAllUser
  register: local_users
  failed_when: false
  when: password_policy_enabled | bool

- name: Debug Local User Accounts
  debug:
    var: local_users
  when: password_policy_enabled | bool

- name: Analyze Current Password Policy
  set_fact:
    password_policy_configured: "{{ current_password_policy.response is defined }}"
    current_min_length: "{{ current_password_policy.response.minLength | default(0) }}"
    current_complexity_rules: "{{ current_password_policy.response.complexityRules | default([]) }}"
  when: 
    - password_policy_enabled | bool
    - current_password_policy.response is defined

- name: Check Password Policy Compliance
  set_fact:
    min_length_compliant: "{{ (current_min_length | int) >= (password_min_length | int) }}"
    complexity_compliant: "{{ (current_complexity_rules | length) >= (password_require_categories | int) }}"
  when: 
    - password_policy_enabled | bool
    - password_policy_configured | default(false)

- name: Determine Overall Password Policy Compliance
  set_fact:
    password_policy_compliant: "{{ (min_length_compliant | default(false)) and (complexity_compliant | default(false)) }}"
  when: password_policy_enabled | bool

- name: Build Required Complexity Rules
  set_fact:
    required_complexity_rules:
      - type: "uppercase"
        enabled: true
      - type: "lowercase" 
        enabled: true
      - type: "numbers"
        enabled: true
      - type: "special"
        enabled: true
  when: password_policy_enabled | bool

- name: Configure Password Policy (if apply_hardening is enabled)
  cisco.fmcansible.fmc_configuration:
    operation: updatePasswordPolicy
    data:
      minLength: "{{ password_min_length }}"
      complexityRules: "{{ required_complexity_rules }}"
      requireCategories: "{{ password_require_categories }}"
      type: "PasswordPolicy"
  register: password_policy_update
  when: 
    - password_policy_enabled | bool
    - apply_hardening | bool
    - not (password_policy_compliant | default(false))

  ## BUG: 404 ?
- name: Debug Password Policy Update Response
  debug:
    var: password_policy_update
  when: 
    - password_policy_enabled | bool
    - apply_hardening | bool

- name: Update Password Policy Compliance After Configuration
  set_fact:
    password_policy_compliant: true
  when: 
    - password_policy_enabled | bool
    - apply_hardening | bool
    - password_policy_update is defined
    - password_policy_update.response is defined

- name: Analyze Local User Accounts
  set_fact:
    local_user_count: "{{ local_users.response.items | length if local_users.response is defined and local_users.response.items is defined else 0 }}"
    local_user_list: "{{ local_users.response.items | map(attribute='name') | list if local_users.response is defined and local_users.response.items is defined else [] }}"
  when: 
    - password_policy_enabled | bool
    - local_users.response is defined

- name: Record Password Policy Compliance Status
  set_fact:
    compliance_results: "{{ compliance_results | default({}) | combine({
      'password_policy_compliance': {
        'status': password_policy_compliant | default(false),
        'min_length_current': current_min_length | default('unknown'),
        'min_length_required': password_min_length,
        'min_length_compliant': min_length_compliant | default(false),
        'complexity_current': current_complexity_rules | default([]),
        'complexity_required': password_require_categories,
        'complexity_compliant': complexity_compliant | default(false),
        'compliant': password_policy_compliant | default(false),
        'local_user_count': local_user_count | default(0),
        'local_users': local_user_list | default([]),
        'applied': (password_policy_update.response is defined) | default(false),
        'recommendation': 'Configure password policy with minimum 15 characters and complexity requirements'
      } }) }}"
  when: password_policy_enabled | bool

- name: Debug Password Policy Compliance Results
  debug:
    var: compliance_results
  when: password_policy_enabled | bool

- name: Display Password Policy Compliance Status
  debug:
    msg:
      - "Password Policy Compliance Check:"
      - "Minimum Length - Current: {{ current_min_length | default('unknown') }}, Required: {{ password_min_length }}, Compliant: {{ min_length_compliant | default(false) }}"
      - "Complexity Rules - Current: {{ (current_complexity_rules | default([])) | length }}, Required: {{ password_require_categories }}, Compliant: {{ complexity_compliant | default(false) }}"
      - "Overall Compliant: {{ password_policy_compliant | default(false) }}"
      - "Local User Accounts: {{ local_user_count | default(0) }}"
      - "{% if local_user_list is defined and local_user_list | length > 0 %}Local Users: {{ local_user_list | join(', ') }}{% endif %}"
      - "{% if apply_hardening and password_policy_update is defined %}Password Policy Applied: {{ password_policy_update.response is defined }}{% endif %}"
  when: password_policy_enabled | bool

- name: Manual Configuration Instructions for Password Policy
  debug:
    msg: |
      MANUAL PASSWORD POLICY CONFIGURATION REQUIRED:
      1. Navigate to System > Users > Password Policy
      2. Set Minimum Password Length: {{ password_min_length }} characters
      3. Enable complexity requirements:
         - Require uppercase letters (A-Z)
         - Require lowercase letters (a-z)
         - Require numbers (0-9)
         - Require special characters
      4. Set "Require at least {{ password_require_categories }} character categories"
      5. Click Save to apply changes
      
      IMPORTANT: Existing user passwords must be updated to meet new policy requirements.
  when: 
    - password_policy_enabled | bool
    - not (password_policy_compliant | default(false))
    - not apply_hardening | bool

- name: Warn About Local User Password Updates
  debug:
    msg: |
      WARNING: Local User Password Updates Required
      The following local user accounts may need password updates to meet the new policy:
      {% for user in local_user_list | default([]) %}
      - {{ user }}
      {% endfor %}
      
      Manual Action Required:
      1. Navigate to System > Users
      2. Edit each local user account
      3. Update passwords to meet new policy requirements
      4. Ensure passwords are at least {{ password_min_length }} characters
      5. Include characters from at least {{ password_require_categories }} categories
  when: 
    - password_policy_enabled | bool
    - local_user_count | default(0) > 0
    - password_policy_update is defined
    - password_policy_update.response is defined
