---
- name: FMC Complete Automation Suite
  hosts: fmc_servers
  gather_facts: true
  vars:
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"
    
  tasks:
    - name: Create all output directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ config_output_dir }}"
        - "{{ trace_output_dir }}"
        - "{{ report_output_dir }}"
        - "{{ log_output_dir }}"
      delegate_to: localhost
      run_once: true

    - name: Display automation suite banner
      debug:
        msg:
          - "=========================================="
          - "    FMC COMPLETE AUTOMATION SUITE"
          - "=========================================="
          - "FMC Host: {{ fmc_host }}"
          - "Timestamp: {{ timestamp }}"
          - "Tasks to execute:"
          - "  1. Connection Test"
          - "  2. Hardening Config Extraction"
          - "  3. Rule Management (if enabled)"
          - "  4. Packet Tracer (if parameters provided)"
          - "=========================================="

    - name: Test FMC Connection
      include_tasks: test_connection_tasks.yml

    - name: Extract Hardening Configuration
      include_tasks: hardening_extraction_tasks.yml
      when: extract_hardening_config | default(true) | bool

    - name: Manage Rules (Time-based)
      include_tasks: rule_management_tasks.yml
      when: 
        - manage_rules | default(true) | bool
        - rule_expiry_check_enabled | default(true) | bool

    - name: Run Packet Tracer
      include_tasks: packet_tracer_tasks.yml
      when: 
        - run_packet_tracer | default(false) | bool
        - source_ip is defined
        - dest_ip is defined

    - name: Display Final Summary
      debug:
        msg:
          - "=========================================="
          - "    AUTOMATION SUITE COMPLETED"
          - "=========================================="
          - "All tasks completed successfully!"
          - "Reports generated in: {{ report_output_dir }}"
          - "Logs available in: {{ log_output_dir }}"
          - "Master report: master_summary_{{ timestamp }}.html"
          - "=========================================="
